apiVersion: apps/v1
kind: Deployment
metadata:
  name: de
  labels:
    app: de
    kubernetes.azure.com/generator: devhub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: de
  template:
    metadata:
      labels:
        app: de
    spec:
      containers:
        - name: de
          image: containernik.azurecr.io/demoapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
